/**
 * Copyright (c) 2013 Contributors - see below
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *    Aziz Nanthaamornphong and Anawat Leathongkum
 */
package edu.ua.front;

import AppPackage.AnimationClass;
import edu.ua.util.GlobalErrorException;
import java.awt.TextArea;
import java.awt.dnd.DropTarget;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileFilter;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

public class FrontUI extends javax.swing.JFrame {

    /**
     * Creates new form FrontUI
     */
    SimpleAttributeSet BOLD_BLACK = new SimpleAttributeSet();
    public FrontUI() {
        initComponents();
        connectToDradDrop();
    }
    int xMouse;
    int yMouse;
    private void connectToDradDrop(){
        DragListener d =new DragListener(textAreaFilelist,fileList);
        new DropTarget(this,d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        fileList = new javax.swing.JList();
        outputText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        statusBox = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaFilelist = new javax.swing.JTextArea();
        close = new javax.swing.JLabel();
        mini = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JLabel();
        buttonRemove = new javax.swing.JLabel();
        buttonReset = new javax.swing.JLabel();
        buttonGenerate = new javax.swing.JLabel();
        buttonView = new javax.swing.JLabel();
        labelFile = new javax.swing.JLabel();
        buttonSave = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel bgFrame = new javax.swing.JLabel();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 80));

        jScrollPane1.setViewportView(fileList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(168, 230, 624, 90);
        getContentPane().add(outputText);
        outputText.setBounds(168, 340, 466, 40);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("LilyUPC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("About");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(750, 30, 30, 24);

        statusBox.setBackground(new java.awt.Color(204, 204, 204));
        statusBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(statusBox);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 500, 624, 90);

        textAreaFilelist.setColumns(20);
        textAreaFilelist.setRows(5);
        jScrollPane2.setViewportView(textAreaFilelist);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(330, 40, 450, 0);

        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(774, 8, 11, 11);

        mini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mini.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniMouseClicked(evt);
            }
        });
        getContentPane().add(mini);
        mini.setBounds(755, 8, 11, 11);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 25);

        buttonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ua/front/add1.png"))); // NOI18N
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonAddMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonAddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAddMouseReleased(evt);
            }
        });
        getContentPane().add(buttonAdd);
        buttonAdd.setBounds(10, 110, 149, 97);

        buttonRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ua/front/remove1.png"))); // NOI18N
        buttonRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRemoveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonRemoveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonRemoveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRemoveMouseReleased(evt);
            }
        });
        getContentPane().add(buttonRemove);
        buttonRemove.setBounds(168, 110, 149, 97);

        buttonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ua/front/reset1.png"))); // NOI18N
        buttonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonResetMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonResetMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonResetMouseReleased(evt);
            }
        });
        getContentPane().add(buttonReset);
        buttonReset.setBounds(326, 110, 149, 97);

        buttonGenerate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ua/front/generate1.png"))); // NOI18N
        buttonGenerate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonGenerateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonGenerateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonGenerateMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonGenerateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonGenerateMouseReleased(evt);
            }
        });
        getContentPane().add(buttonGenerate);
        buttonGenerate.setBounds(484, 110, 149, 97);

        buttonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ua/front/view1.png"))); // NOI18N
        buttonView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonViewMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonViewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonViewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonViewMouseReleased(evt);
            }
        });
        getContentPane().add(buttonView);
        buttonView.setBounds(642, 110, 149, 97);

        labelFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ua/front/file.png"))); // NOI18N
        getContentPane().add(labelFile);
        labelFile.setBounds(10, 230, 149, 90);

        buttonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ua/front/save1.png"))); // NOI18N
        buttonSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSaveMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonSaveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonSaveMouseReleased(evt);
            }
        });
        getContentPane().add(buttonSave);
        buttonSave.setBounds(642, 340, 149, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("LilyUPC", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status/Log");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 477, 60, 24);

        bgFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ua/front/frameGUI.png"))); // NOI18N
        getContentPane().add(bgFrame);
        bgFrame.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void miniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniMouseClicked
        this.setState(FrontUI.ICONIFIED);
    }//GEN-LAST:event_miniMouseClicked

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
         int x = evt.getXOnScreen();
         int y = evt.getYOnScreen();
         this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
         xMouse = evt.getX();
         yMouse = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void buttonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseClicked
        
        JFileChooser fc = new JFileChooser();
        fc.setMultiSelectionEnabled(true);
        FileFilter f90Filter = new ExtensionFileFilter(null, new String[]{"F90"});
        fc.addChoosableFileFilter(f90Filter);
        int returnVal = fc.showOpenDialog(this);
        DefaultListModel listModel = new DefaultListModel();
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File[] files = fc.getSelectedFiles();
            System.out.println("Total Files::"+files.length);
            for (int i = 0; i < files.length; i++) {
                listModel.addElement(files[i].getAbsolutePath());
            }
            this.fileList.setModel(listModel);
        }
        
//        System.out.println("Clicked");
//        AnimationClass ac = new AnimationClass();
//
//        ac.jLabelXRight(40, 560, 10, 2, jLabel2);
//        ac.jTextAreaXRight(40, 560, 10, 2, jScrollPane1);
//        ac.jTextAreaXRight(40, 560, 10, 2, jScrollPane2);
            
    }//GEN-LAST:event_buttonAddMouseClicked

    private void buttonAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/add2.png"));
        buttonAdd.setIcon(II);
    }//GEN-LAST:event_buttonAddMouseEntered

    private void buttonAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/add1.png"));
        buttonAdd.setIcon(II);
    }//GEN-LAST:event_buttonAddMouseExited

    private void buttonAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/add3.png"));
        buttonAdd.setIcon(II);
    }//GEN-LAST:event_buttonAddMousePressed

    private void buttonAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/add2.png"));
        buttonAdd.setIcon(II);

    }//GEN-LAST:event_buttonAddMouseReleased

    private void buttonRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRemoveMouseClicked
         int[] i = this.fileList.getSelectedIndices();
        Object[] obj = this.fileList.getSelectedValues();
        
        DefaultListModel list = (DefaultListModel) this.fileList.getModel();
        for(int j=0; j<i.length;j++){
            list.removeElement(obj[j]);
        }    
 
    }//GEN-LAST:event_buttonRemoveMouseClicked

    private void buttonRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRemoveMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/remove2.png"));
        buttonRemove.setIcon(II);
    }//GEN-LAST:event_buttonRemoveMouseEntered

    private void buttonRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRemoveMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/remove1.png"));
        buttonRemove.setIcon(II);
    }//GEN-LAST:event_buttonRemoveMouseExited

    private void buttonRemoveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRemoveMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/remove3.png"));
        buttonRemove.setIcon(II);
    }//GEN-LAST:event_buttonRemoveMousePressed

    private void buttonRemoveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRemoveMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/remove2.png"));
        buttonRemove.setIcon(II);

    }//GEN-LAST:event_buttonRemoveMouseReleased

    private void buttonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseClicked
        this.fileList.setModel(new DefaultListModel());
        this.outputText.setText("");
        
    }//GEN-LAST:event_buttonResetMouseClicked

    private void buttonResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/reset2.png"));
        buttonReset.setIcon(II);
    }//GEN-LAST:event_buttonResetMouseEntered

    private void buttonResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/reset1.png"));
        buttonReset.setIcon(II);
    }//GEN-LAST:event_buttonResetMouseExited

    private void buttonResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/reset3.png"));
        buttonReset.setIcon(II);
    }//GEN-LAST:event_buttonResetMousePressed

    private void buttonResetMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonResetMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/reset2.png"));
        buttonReset.setIcon(II);

    }//GEN-LAST:event_buttonResetMouseReleased

    private void buttonGenerateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGenerateMouseClicked
        
      try {
            String output = this.outputText.getText();
            if (output.equals("")) {
                JOptionPane.showMessageDialog(this, "Please specify the generated file name", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            File f = new File(output);
            if (f.exists()) {
                int response = JOptionPane.showConfirmDialog(null, "Do you want to replace an existing file?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (response == JOptionPane.NO_OPTION) {
                    return;
                } else if (response == JOptionPane.YES_OPTION) {
                    ParserProcessor front = new ParserProcessor();
                    ListModel listModel = this.fileList.getModel();
                    int size = listModel.getSize();
                    if (size == 0) {
                        JOptionPane.showMessageDialog(this, "Please specify the input(s)", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                    String[] files = new String[size + 1];
                    //   files[0] = "--verbose";
                    files[0] = "--silent";
                    for (int i = 0; i < size; i++) {
                        files[i + 1] = listModel.getElementAt(i).toString();
                    }
                    //front.process(files, output, this.statusTextArea, statusBox);
                    front.process(files, output, statusBox);
                }
            } else {
                ParserProcessor front = new ParserProcessor();
                ListModel listModel = this.fileList.getModel();
                int size = listModel.getSize();
                         
                if (size == 0) {
                    JOptionPane.showMessageDialog(this, "Please specify the input(s)", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                String[] files = new String[size + 1];
                // files[0] = "--verbose";
                files[0] = "--silent";
                for (int i = 0; i < size; i++) {
                    files[i + 1] = listModel.getElementAt(i).toString();
                }
                 front.process(files, output, statusBox);
            }
           String dialogMsg = "";
           int choice = 0;
           if(GlobalErrorException.hasError()){
               dialogMsg = "The XMI document is generated with the warning. Do you want to view the UML?";
                choice = JOptionPane.showConfirmDialog(this, dialogMsg, "ForUML", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
           }else{
               dialogMsg = "The XMI document is completely generated. Do you want to view the UML?";
                choice = JOptionPane.showConfirmDialog(this, dialogMsg, "ForUML", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
           }
          
           if(choice == JOptionPane.YES_OPTION){
               executeArgoUML();
           }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,GlobalErrorException.getError(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();           
        }
        
    }//GEN-LAST:event_buttonGenerateMouseClicked

    private void buttonGenerateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGenerateMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/generate2.png"));
        buttonGenerate.setIcon(II);
    }//GEN-LAST:event_buttonGenerateMouseEntered

    private void buttonGenerateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGenerateMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/generate1.png"));
        buttonGenerate.setIcon(II);
    }//GEN-LAST:event_buttonGenerateMouseExited

    private void buttonGenerateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGenerateMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/generate3.png"));
        buttonGenerate.setIcon(II);
    }//GEN-LAST:event_buttonGenerateMousePressed

    private void buttonGenerateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonGenerateMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/generate2.png"));
        buttonGenerate.setIcon(II);
    }//GEN-LAST:event_buttonGenerateMouseReleased

    private void buttonViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonViewMouseClicked
        executeArgoUML();

    }//GEN-LAST:event_buttonViewMouseClicked

    private void buttonViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonViewMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/view2.png"));
        buttonView.setIcon(II);
    }//GEN-LAST:event_buttonViewMouseEntered

    private void buttonViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonViewMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/view1.png"));
        buttonView.setIcon(II);
    }//GEN-LAST:event_buttonViewMouseExited

    private void buttonViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonViewMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/view3.png"));
        buttonView.setIcon(II);
    }//GEN-LAST:event_buttonViewMousePressed

    private void buttonViewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonViewMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/view2.png"));
        buttonView.setIcon(II);

    }//GEN-LAST:event_buttonViewMouseReleased

    private void buttonSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSaveMouseClicked
         JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        fc.setSelectedFile(new File(System.getProperty("user.dir") + System.getProperty("file.separator") + "output.xmi"));
      
        int returnVal = fc.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            this.outputText.setText(file.getAbsolutePath());
        }
      
    }//GEN-LAST:event_buttonSaveMouseClicked

    private void buttonSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSaveMouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/save2.png"));
        buttonSave.setIcon(II);
    }//GEN-LAST:event_buttonSaveMouseEntered

    private void buttonSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSaveMouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/save1.png"));
        buttonSave.setIcon(II);
    }//GEN-LAST:event_buttonSaveMouseExited

    private void buttonSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSaveMousePressed
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/save3.png"));
        buttonSave.setIcon(II);
    }//GEN-LAST:event_buttonSaveMousePressed

    private void buttonSaveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSaveMouseReleased
        ImageIcon II = new ImageIcon(getClass().getResource("/edu/ua/front/save2.png"));
        buttonSave.setIcon(II);

    }//GEN-LAST:event_buttonSaveMouseReleased

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        AnimationClass ac = new AnimationClass();
        ac.jTextAreaYUp(500, 390, 10, 2, jScrollPane3);
        ac.jTextAreaYDown(390, 500, 10, 2, jScrollPane3);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void executeArgoUML() {
       StyleConstants.setBold(BOLD_BLACK, true); 
       try{
          statusBox.getDocument().insertString(statusBox.getDocument().getLength(), "Launching ArgoUML"+System.getProperty("line.separator"), BOLD_BLACK);
        }catch(Exception ex){}
        org.argouml.application.Main main = new org.argouml.application.Main();
        String params[] = new String[2];
        params[0] = "-open";
        //params[1] = "/Users/aziznanthaamornphong/Documents/tmp/test101.xmi";
        params[1] = this.outputText.getText();
        main.runByForUML(params);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      System.setProperty("apple.laf.useScreenMenuBar", "true");
      System.setProperty("com.apple.mrj.application.apple.menu.about.name", "WikiTeX");
    try {
      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    } catch (ClassNotFoundException ex) {
      Logger.getLogger(FrontUI.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      Logger.getLogger(FrontUI.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      Logger.getLogger(FrontUI.class.getName()).log(Level.SEVERE, null, ex);
    } catch (UnsupportedLookAndFeelException ex) {
      Logger.getLogger(FrontUI.class.getName()).log(Level.SEVERE, null, ex);
    }
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrontUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrontUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrontUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrontUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrontUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonAdd;
    private javax.swing.JLabel buttonGenerate;
    private javax.swing.JLabel buttonRemove;
    private javax.swing.JLabel buttonReset;
    private javax.swing.JLabel buttonSave;
    private javax.swing.JLabel buttonView;
    private javax.swing.JLabel close;
    private javax.swing.JList fileList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelFile;
    private javax.swing.JLabel mini;
    private javax.swing.JTextField outputText;
    private javax.swing.JTextPane statusBox;
    private javax.swing.JTextArea textAreaFilelist;
    // End of variables declaration//GEN-END:variables
}
